blog_baris_aslan/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_view, name="register"),
    path('logout/', logout_view, name="logout"),
]

blog_baris_aslan/blog_baris_aslan/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import homeView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeView, name='home'),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_baris_aslan/post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('index/', postIndex, name="index"),
    path('<slug:slug>/detail/', postDetail, name="detail"),
    path('create/', postCreate, name="create"),
    path('<slug:slug>/update/', postUpdate, name="update"),
    path('<slug:slug>/delete/', postDelete, name="delete"),
]

blog_baris_aslan/home/models.py
from django.db import models

# Create your models here.

blog_baris_aslan/home/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def homeView(request):
    if request.user.is_authenticated:
        context = {
            'isim': 'Selçuk'
        }
    else:
        context = {
            'isim': 'Misafir Kullanıcı'
        }
    return render(request, 'home.html', context)

blog_baris_aslan/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Dersleri{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{#    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>#}
{#    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>#}
</head>
<body>

{% include 'header.html' %}

{% include 'messages.html' %}

{% block body %}

{%  endblock %}


<script src="{%  static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

blog_baris_aslan/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top ">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <!--- Temel sayfalar ---->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link " href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'post:index' %}">Blog</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{%  url 'post:create' %}">Yazı Ekle</a>
                </li>
            {% endif %}

            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">Üye ol</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Giriş</a>
                </li>

            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış</a>
                </li>
            {% endif %}
        </ul>

        <!--- Arama Çubuğu --->
        <form class="form-inline">
            <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
        </form>

    </div>
</nav>

blog_baris_aslan/templates/home.html
{% extends 'base.html' %}

{% block title %} Anasayfa - {{ block.super }} {% endblock %}

{%  block body %}


    <div class="container-fluid">
{#        <div class="row" style="margin-bottom: 30px ">#}
{#            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px">1. ürün</div>#}
{#            <div class="col-md-3 col-sm-6 " style="background-color: black; height: 100px">2. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: orange; height: 100px">3. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px">4. ürün</div>#}
{#        </div>#}
{#        <div class="row" style="margin-bottom: 30px ">#}
{#            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px">1. ürün</div>#}
{#            <div class="col-md-3 col-sm-6 " style="background-color: black; height: 100px">2. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: orange; height: 100px">3. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px">4. ürün</div>#}
{#        </div>#}
{#        <div class="row" style="margin-bottom: 30px ">#}
{#            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px">1. ürün</div>#}
{#            <div class="col-md-3 col-sm-6 " style="background-color: black; height: 100px">2. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: orange; height: 100px">3. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px">4. ürün</div>#}
{#        </div>#}
{#        <div class="row" style="margin-bottom: 30px ">#}
{#            <div class="col-md-3 col-sm-6" style="background-color: red; height: 100px">1. ürün</div>#}
{#            <div class="col-md-3 col-sm-6 " style="background-color: black; height: 100px">2. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: orange; height: 100px">3. ürün</div>#}
{#            <div class="col-md-3 col-sm-6" style="background-color: blue; height: 100px">4. ürün</div>#}
{#        </div>#}
    <div class="row">
        <div class="col-md-4" style="background-color:green; height:100px"></div>
        <div class="col-md-8" style="background-color:pink; height:100px">
            <div class="row">
                <div class="col-md-2" style="background-color: red; height:100px;"></div>
                <div class="col-md-6" style="background-color: blue; height:100px;"></div>
                <div class="col-md-4" style="background-color: grey; height:100px;"></div>
            </div>
        </div>
    </div>
    <h5>Hoşgeldiniz, {{ request.user.get_full_name }}</h5>
    </div>

{% endblock %}

blog_baris_aslan/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{message}}
        </div>
    {% endfor %}
{% endif %}